models/Ipt.php
<?php

namespace app\models;

use Yii;
use DateTime;
/**
 * This is the model class for table "ipt".
 *
 * @property int $vn
 * @property int $an
 * @property int $hn
 * @property string $ward
 * @property string $rgtdate
 * @property int $rgttime
 * @property string $pttype
 * @property string $prediag
 * @property string $dchdate
 * @property int $daycnt
 * @property int $dchtime
 * @property int $dchstts
 * @property int $dchtype
 * @property string $dthdiagdct
 * @property string $ipdlct
 * @property float|null $bmi
 * @property float $bw
 * @property float|null $height
 * @property float|null $tt
 * @property int $rr
 * @property int $pr
 * @property int $sbp
 * @property int $dbp
 * @property string $ipttype
 * @property int $painscore
 * @property string|null $symptmi
 * @property string|null $drg
 * @property float|null $rw
 * @property float|null $adjrw
 * @property string|null $error
 * @property string|null $warning
 * @property int|null $actlos
 * @property string|null $grouper_version
 * @property float|null $wtlos
 * @property int|null $ot
 * @property string|null $dept
 */
class Ipt extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'ipt';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['vn', 'an', 'hn', 'rgttime', 'pttype', 'prediag', 'daycnt', 'dchtime', 'dchstts', 'dchtype', 'dthdiagdct', 'ipdlct', 'bw', 'rr', 'pr', 'sbp', 'dbp', 'ipttype', 'painscore'], 'required'],
            [['vn', 'an', 'hn', 'rgttime', 'daycnt', 'dchtime', 'dchstts', 'dchtype', 'rr', 'pr', 'sbp', 'dbp', 'painscore', 'actlos', 'ot'], 'integer'],
            [['rgtdate', 'dchdate'], 'safe'],
            [['bmi', 'bw', 'height', 'tt', 'rw', 'adjrw', 'wtlos'], 'number'],
            [['ward', 'pttype', 'ipttype', 'error', 'dept'], 'string', 'max' => 2],
            [['prediag'], 'string', 'max' => 7],
            [['dthdiagdct', 'ipdlct', 'drg'], 'string', 'max' => 5],
            [['symptmi'], 'string', 'max' => 1000],
            [['warning'], 'string', 'max' => 4],
            [['grouper_version'], 'string', 'max' => 20],
            [['an'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'vn' => 'Vn',
            'an' => 'An',
            'hn' => 'Hn',
            'ward' => 'Ward',
            'rgtdate' => 'Rgtdate',
            'rgttime' => 'Rgttime',
            'pttype' => 'Pttype',
            'prediag' => 'Prediag',
            'dchdate' => 'Dchdate',
            'daycnt' => 'Daycnt',
            'dchtime' => 'Dchtime',
            'dchstts' => 'Dchstts',
            'dchtype' => 'Dchtype',
            'dthdiagdct' => 'Dthdiagdct',
            'ipdlct' => 'Ipdlct',
            'bmi' => 'Bmi',
            'bw' => 'Bw',
            'height' => 'Height',
            'tt' => 'Tt',
            'rr' => 'Rr',
            'pr' => 'Pr',
            'sbp' => 'Sbp',
            'dbp' => 'Dbp',
            'ipttype' => 'Ipttype',
            'painscore' => 'Painscore',
            'symptmi' => 'Symptmi',
            'drg' => 'Drg',
            'rw' => 'Rw',
            'adjrw' => 'Adjrw',
            'error' => 'Error',
            'warning' => 'Warning',
            'actlos' => 'Actlos',
            'grouper_version' => 'Grouper Version',
            'wtlos' => 'Wtlos',
            'ot' => 'Ot',
            'dept' => 'Dept',
        ];
    }

    public function getWardadmit()
    {
        return $this->hasOne(Idpm::className(),['idpm' => 'ward']);
    }

    public function getIptadm()
    {
        return $this->hasOne(Iptadm::className(),['an' => 'an']);
    }

    public function getDctype()
    {
        return $this->hasOne(Dchtype::className(),['dchtype' => 'dchtype']);
    }
    
    public function getPt()
    {
        return $this->hasOne(Pt::className(),['hn' => 'hn']);
    }

    public function getRefer()
    {
        return $this->hasOne(Orfro::className(),['vn' => 'vn']);
    }

    public function getDcDate()
    {
        $month = array("01"=>"ม.ค.","02"=>"ก.พ","03"=>"มี.ค.","04"=>"เม.ย.","05"=>"พ.ค.","06"=>"มิ.ย.","07"=>"ก.ค.","08"=>"ส.ค.","09"=>"ก.ย.","10"=>"ต.ค.","11"=>"พ.ย.","12"=>"ธ.ค.");
        $visit = new DateTime($this->dchdate);
        $d = $visit->format('j');
        $m = $month[$visit->format('m')];
        $y = $visit->format('Y')+543;
        if(strlen($this->dchtime) == 4){
            $h = substr($this->dchtime,0,2);
            $i = substr($this->dchtime,2,2);
        } else {
            $h = '0'.substr($this->dchtime,0,1);
            $i = substr($this->dchtime,1,2);
        } 
        $result = $d.' '.$m.' '.$y.' เวลา '.$h.':'.$i.' น.';
        return $result;

    }

    public function getAdmitDate()
    {
        $month = array("01"=>"ม.ค.","02"=>"ก.พ","03"=>"มี.ค.","04"=>"เม.ย.","05"=>"พ.ค.","06"=>"มิ.ย.","07"=>"ก.ค.","08"=>"ส.ค.","09"=>"ก.ย.","10"=>"ต.ค.","11"=>"พ.ย.","12"=>"ธ.ค.");
        $visit = new DateTime($this->rgtdate);
        $d = $visit->format('j');
        $m = $month[$visit->format('m')];
        $y = $visit->format('Y')+543;
        if(strlen($this->rgttime) == 4){
            $h = substr($this->rgttime,0,2);
            $i = substr($this->rgttime,2,2);
        } else {
            $h = '0'.substr($this->rgttime,0,1);
            $i = substr($this->rgttime,1,2);
        } 
        $result = $d.' '.$m.' '.$y.' เวลา '.$h.':'.$i.' น.';
        return $result;
    }

    public static function getThaiDate($date)
    {
        $month = array("01"=>"ม.ค.","02"=>"ก.พ","03"=>"มี.ค.","04"=>"เม.ย.","05"=>"พ.ค.","06"=>"มิ.ย.","07"=>"ก.ค.","08"=>"ส.ค.","09"=>"ก.ย.","10"=>"ต.ค.","11"=>"พ.ย.","12"=>"ธ.ค.");
        if($date){
            $visit = new DateTime($date);
            $d = $visit->format('j');
            $m = $month[$visit->format('m')];
            $y = $visit->format('Y')+543;
            $result = $d.' '.$m.' '.$y;    
        } else {
            $result = 'ไม่ได้ระบุวัน';
        }
        return $result;
    }

    public static function getThaiDateTime($date)
    {
        $month = array("01"=>"ม.ค.","02"=>"ก.พ","03"=>"มี.ค.","04"=>"เม.ย.","05"=>"พ.ค.","06"=>"มิ.ย.","07"=>"ก.ค.","08"=>"ส.ค.","09"=>"ก.ย.","10"=>"ต.ค.","11"=>"พ.ย.","12"=>"ธ.ค.");
        if($date){
            $visit = new DateTime($date);
            $d = $visit->format('j');
            $m = $month[$visit->format('m')];
            $y = $visit->format('Y')+543;
            $h = $visit->format('H');
            $i = $visit->format('i');
            $result = $d.' '.$m.' '.$y.' '.$h.':'.$i.'  น.'  ;    
        } else {
            $result = 'ไม่ได้ระบุวัน';
        }
        return $result;
    }

    public function getReceive(){
        $order = DoctorOrders::find()->where(['an' => $this->an])->andWhere('receive_id is null')->one();
        if($order){
            return 'btn btn-danger btn-block';
        }   
        return 'btn btn-success btn-block';
    }

}

models/Pt.php
<?php

namespace app\models;

use Yii;
use DateTime;
/**
 * This is the model class for table "pt".
 *
 * @property int $hn
 * @property string $pname
 * @property string $fname
 * @property string $lname
 * @property string $brthdate
 * @property int $truebrth
 * @property string $dthdate
 * @property string $male
 * @property string $ctzshp
 * @property string $ntnlty
 * @property string $rlgn
 * @property string $occptn
 * @property string $bloodgrp
 * @property string $allergy
 * @property string $addrpart
 * @property string $moopart
 * @property string $tmbpart
 * @property string $amppart
 * @property string $chwpart
 * @property string $hometel
 * @property string $pttype
 * @property string $mrtlst
 * @property string $spsname
 * @property string $mthname
 * @property string $fthname
 * @property string $offaddr
 * @property string $offtel
 * @property string $infmname
 * @property string $prsnrlt
 * @property string $infmaddr
 * @property string $infmtel
 * @property string $opdlct
 * @property string $fdate
 * @property string $ldate
 * @property string $pop_id
 * @property string $height
 * @property string $register
 * @property string $pathimage
 * @property string $typearea
 * @property string $statusinfo
 * @property string $house_id
 * @property string $housetype
 * @property string $viptype
 * @property string $cidlabor
 * @property string $engfname
 * @property string $englname
 * @property string $engpname
 * @property string $familyno
 * @property string $father_cid
 * @property string $mother_cid
 * @property string $couple_cid
 * @property string $family_pos
 * @property string $movein
 * @property string $moveout
 * @property string $typedisch
 * @property string $labor
 * @property string $passport
 * @property string $vstatus
 * @property string $gencid
 * @property string $education
 * @property string $couple
 */
class Pt extends \yii\db\ActiveRecord
{
    public $total;
    
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'pt';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['pname', 'truebrth', 'male', 'ctzshp', 'ntnlty', 'rlgn', 'occptn', 'bloodgrp', 'allergy', 'addrpart', 'moopart', 'tmbpart', 'amppart', 'chwpart', 'hometel', 'pttype', 'mrtlst', 'spsname', 'mthname', 'fthname', 'offaddr', 'offtel', 'infmname', 'prsnrlt', 'infmaddr', 'infmtel', 'opdlct', 'pop_id', 'height', 'register', 'statusinfo', 'house_id', 'housetype', 'viptype', 'cidlabor', 'engfname', 'englname', 'engpname', 'father_cid', 'mother_cid', 'couple_cid', 'passport', 'vstatus', 'gencid', 'education', 'couple'], 'required'],
            [['brthdate', 'dthdate', 'fdate', 'ldate', 'movein', 'moveout'], 'safe'],
            [['truebrth'], 'integer'],
            [['height'], 'number'],
            [['typearea'], 'string'],
            [['pname'], 'string', 'max' => 15],
            [['fname', 'lname'], 'string', 'max' => 25],
            [['male', 'rlgn', 'mrtlst', 'housetype', 'family_pos', 'typedisch', 'vstatus'], 'string', 'max' => 1],
            [['ctzshp', 'ntnlty', 'bloodgrp', 'moopart', 'tmbpart', 'amppart', 'chwpart', 'pttype', 'register', 'viptype', 'labor', 'education'], 'string', 'max' => 2],
            [['occptn'], 'string', 'max' => 3],
            [['allergy'], 'string', 'max' => 60],
            [['addrpart', 'spsname', 'mthname', 'fthname', 'infmname'], 'string', 'max' => 30],
            [['hometel', 'offtel', 'infmtel', 'cidlabor', 'passport'], 'string', 'max' => 20],
            [['offaddr', 'infmaddr'], 'string', 'max' => 150],
            [['prsnrlt'], 'string', 'max' => 10],
            [['opdlct'], 'string', 'max' => 5],
            [['pop_id', 'familyno', 'father_cid', 'mother_cid', 'couple_cid', 'gencid'], 'string', 'max' => 13],
            [['pathimage', 'couple'], 'string', 'max' => 100],
            [['statusinfo', 'engfname', 'englname', 'engpname'], 'string', 'max' => 40],
            [['house_id'], 'string', 'max' => 11],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'hn' => 'Hn',
            'pname' => 'Pname',
            'fname' => 'Fname',
            'lname' => 'Lname',
            'brthdate' => 'Brthdate',
            'truebrth' => 'Truebrth',
            'dthdate' => 'Dthdate',
            'male' => 'Male',
            'ctzshp' => 'Ctzshp',
            'ntnlty' => 'Ntnlty',
            'rlgn' => 'Rlgn',
            'occptn' => 'Occptn',
            'bloodgrp' => 'Bloodgrp',
            'allergy' => 'Allergy',
            'addrpart' => 'Addrpart',
            'moopart' => 'Moopart',
            'tmbpart' => 'Tmbpart',
            'amppart' => 'Amppart',
            'chwpart' => 'Chwpart',
            'hometel' => 'Hometel',
            'pttype' => 'Pttype',
            'mrtlst' => 'Mrtlst',
            'spsname' => 'Spsname',
            'mthname' => 'Mthname',
            'fthname' => 'Fthname',
            'offaddr' => 'Offaddr',
            'offtel' => 'Offtel',
            'infmname' => 'Infmname',
            'prsnrlt' => 'Prsnrlt',
            'infmaddr' => 'Infmaddr',
            'infmtel' => 'Infmtel',
            'opdlct' => 'Opdlct',
            'fdate' => 'Fdate',
            'ldate' => 'Ldate',
            'pop_id' => 'Pop ID',
            'height' => 'Height',
            'register' => 'Register',
            'pathimage' => 'Pathimage',
            'typearea' => 'Typearea',
            'statusinfo' => 'Statusinfo',
            'house_id' => 'House ID',
            'housetype' => 'Housetype',
            'viptype' => 'Viptype',
            'cidlabor' => 'Cidlabor',
            'engfname' => 'Engfname',
            'englname' => 'Englname',
            'engpname' => 'Engpname',
            'familyno' => 'Familyno',
            'father_cid' => 'Father Cid',
            'mother_cid' => 'Mother Cid',
            'couple_cid' => 'Couple Cid',
            'family_pos' => 'Family Pos',
            'movein' => 'Movein',
            'moveout' => 'Moveout',
            'typedisch' => 'Typedisch',
            'labor' => 'Labor',
            'passport' => 'Passport',
            'vstatus' => 'Vstatus',
            'gencid' => 'Gencid',
            'education' => 'Education',
            'couple' => 'Couple',
        ];
    }

    public function getAge()
    {
        $dob = new DateTime($this->brthdate);
        $today = new DateTime('today');
        $age = $dob->diff($today)->y;
        return $age.' ปี';
    }

    public function getFullname()
    {
        $dob = new DateTime($this->brthdate);
        $today = new DateTime('today');
        $age = $dob->diff($today)->y;
        if($this->pname == '') {
            if($this->male == '1' && $age < 15 ) {
                $this->mrtlst <> '6' ? $this->pname = 'ด.ช.': $this->pname = 'เณร';
            }  
            if($this->male == '1' && $age >= 15 ) {
                $this->mrtlst <> '6' ? $this->pname = 'นาย': $this->pname = 'พระ';
            }
            if($this->male == '2' && $age >= 15 ) {
                $this->mrtlst == '2' ? $this->pname = 'นาง': $this->pname = 'นางสาว';
            }
            if($this->male == '2' && $age >= 15 && $this->mrtlst == '6' ) {
                $this->pname = 'แม่ชี';
            }  
            if($this->male == '2' && $age < 15 ) {
                $this->pname = 'ด.ญ.';
            }
        }  
        return $this->pname.$this->fname.' '.$this->lname;
    }

    public function getฺBirthdate()
    {
        $month = array("01"=>"ม.ค.","02"=>"ก.พ","03"=>"มี.ค.","04"=>"เม.ย.","05"=>"พ.ค.","06"=>"มิ.ย.","07"=>"ก.ค.","08"=>"ส.ค.","09"=>"ก.ย.","10"=>"ต.ค.","11"=>"พ.ย.","12"=>"ธ.ค.");
        $visit = new DateTime($this->brthdate);
        $d = $visit->format('j');
        $m = $month[$visit->format('m')];
        $y = $visit->format('Y')+543;
        $result = $d.' '.$m.' '.$y;
        return $result;
    }

    public function getGender(){
        return $this->male == '1' ? 'ชาย':'หญิง';
    }

    public function getType()
    {
        return $this->hasOne(Pttype::className(),['pttype' => 'pttype']);
    }

}

views/order/_order.php
<?php

use yii\helpers\Html;
use app\models\Admission;
use app\models\Ipt;

?>
<h3 align="center"><?= $office->value2 ?><br><?= $office->value3 ?> <?= $office->values4 ?>
  <br>Doctor Orders Sheet & Progress Note
</h3>
<table calss="table_bordered" width="100%" border="1" cellpadding="2" cellspacing="0">
  <tr>
    <td width="35%" style="padding-left:5px;padding-right:5px;"><b>ชื่อ-สกุล </b><br>&emsp; &emsp; &emsp;<?= $pt->pt->getFullName() ?></td>
    <td width="25%"><b>&emsp;Ward </b> <?= $order->getWardname() ?><br>&emsp; <b>Bed</b> <?= $order->bed_no ?></td>
    <td width="20%">&emsp; <b>อายุ</b> <?= $pt->pt->getAge() ?> ปี<br>&emsp; <b>เพศ </b> <?= $pt->pt->getGender() ?></td>
    <td width="20%">&emsp; <b>HN:</b> <?= $pt->hn ?><br>&emsp; <b>AN:</b> <?= $pt->an ?></td>
  </tr>
</table>
<table calss="table_bordered" width="100%" border="1" cellpadding="2" cellspacing="0">
  <tr>
    <th width="24%">Progress Note</th>
    <th width="28%">Order One Day</th>
    <th width="28%">Order Continue</th>
    <th width="20%">หมายเหตุ</th>
  </tr>
  <tr>
    <td height=700 valign=top style="padding-left:5px;padding-right:5px;">
      <?= Ipt::getThaiDateTime($order->order_datetime) ?><br>
      <?= $order->specialist_progress_note ? $order->getProgName() . '<br>' : '' ?>
      <?= $order->progress_note ?><br>
      <b>Order By :</b><br>
      <?= $order->profile->fullname ?><br>
      <?= $order->profile->position ?><br>
      <?= $order->profile->license_no ?><br>
      <?= $order->receive_id ? '<b>รับ Order : </b>'.$order->receive->fullname.'<br>'.$order->receive->position:'' ?>

    <td valign=top style="padding-left:5px;padding-right:5px;">
      <?= $order->labs ? '<b><u>Lab</u> ::</b><br>' . $order->getLabsName() . '<br>' : '' ?>
      <?= $order->xrays ? '<b><u>X-Ray</u> ::</b><br>' . $order->getXraysName() . '<br>' : '' ?>
      <?= $order->order_oneday ?>
    <td valign=top style="padding-left:5px;padding-right:5px;">
      <?= $order->food ? $order->getFoodName() : '' ?>
      <?= $order->extra_food ? ' ระบุ ' . $order->extra_food . '<br>' : '<br>' ?>
      <?= $order->record_io ? '&emsp; [ / ] Record I/O <br>' : '' ?>
      <?= $order->record_vitalsign ? '&emsp; [ / ] Record V/S <br>' : '' ?>
      <?= $order->order_continue ? nl2br($order->order_continue) : '' ?>
      <?php /*
      foreach ($order->getContinueOrders() as $c) {
        echo Ipt::getThaiDateTime($c->order_datetime) . '<br>';
        echo nl2br($c->order_continue) . '<br>';
      } */
      ?>
    </td>
    <td style="padding-left:5px;padding-right:5px;vertical-align:top;">
      <?= $order->order_comment ?>
      <br><br>
      <?= $order->receive_id ? '<b>รับ Order By:</b>' : '' ?><br>
      <?= $order->receive->fullname ?><br>
      <?= $order->receive->position ?><br>
    </td>
  </tr>
</table>
<hr>

views/order/_print.php
<?php

use yii\helpers\Html;
use app\models\Admission;
use app\models\Ipt;

function thaimonth($m)
{
  switch ($m) {
    case '01':
      $thainame = 'มกราคม';
      break;
    case '02':
      $thainame = 'กุมภาพันธ์';
      break;
    case '03':
      $thainame = 'มีนาคม';
      break;
    case '04':
      $thainame = 'เมษายน';
      break;
    case '05':
      $thainame = 'พฤษภาคม';
      break;
    case '06':
      $thainame = 'มิถุนายน';
      break;
    case '07':
      $thainame = 'กรกฎาคม';
      break;
    case '08':
      $thainame = 'สิงหาคม';
      break;
    case '09':
      $thainame = 'กันยายน';
      break;
    case '10':
      $thainame = 'ตุลาคม';
      break;
    case '11':
      $thainame = 'พฤศจิกายน';
      break;
    case '12':
      $thainame = 'ธันวาคม';
      break;
  }
  return $thainame;
}
?>
<?php
$page = 1;
$row = 0;
foreach ($model as $order) {
  if ($page <> 1 && $row % 2 == 1 && $row > 2 || $row == 1) {
    echo '<pagebreak>';
    $page++;
  }
  $row++;
  // echo '- '.$page.' - '.$row;
?>
  <?php
  if ($page == 1 || $row % 2 == 0) {
  ?>
    <h3 align="center"><?= $office->value2 ?><br><?= $office->value3 ?> <?= $office->values4 ?>
      <br>Doctor Orders Sheet & Progress Note
    </h3>
  <?php
  }
  ?>
  <table calss="table_bordered" width="100%" border="1" cellpadding="2" cellspacing="0">
    <tr>
      <?php
      if ($page == 1 || $row % 2 == 0) {
      ?>
        <td width="35%"><b>&emsp; ชื่อ-สกุล </b><br>&emsp; &emsp; &emsp;<?= $pt->pt->getFullName() ?></td>
        <td width="25%"><b>&emsp;Ward </b> <?= $order->getWardname() ?><br>&emsp; <b>Bed</b> <?= $order->bed_no ?></td>
        <td width="20%">&emsp; <b>อายุ</b> <?= $pt->pt->getAge() ?><br>&emsp; <b>เพศ </b> <?= $pt->pt->getGender() ?></td>
        <td width="20%">&emsp; <b>HN:</b> <?= $pt->hn ?><br>&emsp; <b>AN:</b> <?= $pt->an ?></td>
      <?php
      } else {
        echo '<td colspan="4"><b>&emsp;Ward </b>' . $order->getWardname() . ' &emsp; <b>Bed</b> ' . $order->bed_no . '</td>';
      }
      ?>
    </tr>
  </table>
  <table calss="table_bordered" width="100%" border="1" cellpadding="2" cellspacing="0">
    <tr>
      <th width="25%">Progress Note</th>
      <th width="25%">Order One Day</th>
      <th width="35%">Order Continue</th>
      <th width="15%">หมายเหตุ</th>
    </tr>
    <tr>
      <?php if ($row == 1) {
        echo '<td height=720 valign=top style="padding-left:5px;padding-right:5px;">';
      } else {
        echo '<td height=350 valign=top style="padding-left:5px;padding-right:5px;">';
      }
      ?>
      <?= Ipt::getThaiDateTime($order->order_datetime) ?><br>
      <?= $order->specialist_progress_note ? $order->getProgName() . '<br>' : '' ?>
      <?= nl2br($order->progress_note) ?><br>
      <b>Order By :</b><br>
      <?= $order->profile->fullname ?><br>
      <?= $order->profile->position ?><br>
      <?= $order->profile->license_no ?><br>
      <?= $order->receive_id ? '<b>รับ Order : </b>'.$order->receive->fullname.'<br>'.$order->receive->position:'' ?>

      <td valign=top style="padding-left:5px;padding-right:5px;">
        <?= $order->labs ? '<b><u>Lab</u> ::</b><br>' . $order->getLabsName() . '<br>' : '' ?>
        <?= $order->xrays ? '<b><u>X-Ray</u> ::</b><br>' . $order->getXraysName() . '<br>' : '' ?>
        <?= nl2br($order->order_oneday) ?>
      <td valign=top style="padding-left:5px;padding-right:5px;">
        <?= $order->food ? $order->getFoodName() : '' ?>
        <?= $order->extra_food ? ' ระบุ ' . $order->extra_food . '<br>' : '<br>' ?>
        <?= $order->record_io ? '&emsp; [ / ] Record I/O <br>' : '' ?>
        <?= $order->record_vitalsign ? '&emsp; [ / ] Record V/S <br>' : '' ?>
        <?= $order->order_continue ? nl2br($order->order_continue) : '' ?>
      </td>
      <td style="padding-left:5px;padding-right:5px;vertical-align:top">
        <?= $order->order_comment ?>
        <br>
        <?= $order->receive_id ? '<b>รับ Order By:</b>' : '' ?>
        <?= $order->receive->fullname ?><br>
        <?= $order->receive->position ?><br>
      </td>
    </tr>
  </table>
<?php

} ?>

views/order/_search.php
<?php

use kartik\icons\Icon;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\DoctorOrdersSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="doctor-orders-search">

    <?php $form = ActiveForm::begin([
        'action' => ['list-order', 'ward_id' => $ward_id],
        'method' => 'get',
    ]); ?>
    <div class="row">
        <div class="col-md-3 col-sm-6 col-sx-8">
            <?= $form->field($model, 'an')->textInput(['placeholder' => 'ระบุ AN'])->label(false) ?>
        </div>
        <div class="col-2">
            <div class="form-group">
                <?= Html::submitButton(Icon::show('search'), ['class' => 'btn btn-primary']) ?>
            </div>
        </div>
    </div>


    <?php ActiveForm::end(); ?>

</div>

views/order/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\DoctorOrders */

$this->title = 'Orders:'.$admit->pt->getFullName();
?>
<div class="doctor-orders-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/order/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\DoctorOrdersSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Doctor Orders';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="doctor-orders-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Doctor Orders', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'order_id',
            'an',
            'order_datetime',
            'progress_note:ntext',
            'order_oneday:ntext',
            //'order_continue:ntext',
            //'order_comment:ntext',
            //'user_id',
            //'d_update',
            [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action, $model, $key, $index, $column) {
                    return Url::toRoute([$action, 'order_id' => $model->order_id]);
                 }
            ],
        ],
    ]); ?>


</div>

views/order/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\DoctorOrders */

$this->title = 'Update Doctor Orders: ' . $model->order_id;
?>
<div class="doctor-orders-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>