models/Ipt.php
<?php

namespace app\models;

use Yii;
use DateTime;
/**
 * This is the model class for table "ipt".
 *
 * @property int $vn
 * @property int $an
 * @property int $hn
 * @property string $ward
 * @property string $rgtdate
 * @property int $rgttime
 * @property string $pttype
 * @property string $prediag
 * @property string $dchdate
 * @property int $daycnt
 * @property int $dchtime
 * @property int $dchstts
 * @property int $dchtype
 * @property string $dthdiagdct
 * @property string $ipdlct
 * @property float|null $bmi
 * @property float $bw
 * @property float|null $height
 * @property float|null $tt
 * @property int $rr
 * @property int $pr
 * @property int $sbp
 * @property int $dbp
 * @property string $ipttype
 * @property int $painscore
 * @property string|null $symptmi
 * @property string|null $drg
 * @property float|null $rw
 * @property float|null $adjrw
 * @property string|null $error
 * @property string|null $warning
 * @property int|null $actlos
 * @property string|null $grouper_version
 * @property float|null $wtlos
 * @property int|null $ot
 * @property string|null $dept
 */
class Ipt extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'ipt';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['vn', 'an', 'hn', 'rgttime', 'pttype', 'prediag', 'daycnt', 'dchtime', 'dchstts', 'dchtype', 'dthdiagdct', 'ipdlct', 'bw', 'rr', 'pr', 'sbp', 'dbp', 'ipttype', 'painscore'], 'required'],
            [['vn', 'an', 'hn', 'rgttime', 'daycnt', 'dchtime', 'dchstts', 'dchtype', 'rr', 'pr', 'sbp', 'dbp', 'painscore', 'actlos', 'ot'], 'integer'],
            [['rgtdate', 'dchdate'], 'safe'],
            [['bmi', 'bw', 'height', 'tt', 'rw', 'adjrw', 'wtlos'], 'number'],
            [['ward', 'pttype', 'ipttype', 'error', 'dept'], 'string', 'max' => 2],
            [['prediag'], 'string', 'max' => 7],
            [['dthdiagdct', 'ipdlct', 'drg'], 'string', 'max' => 5],
            [['symptmi'], 'string', 'max' => 1000],
            [['warning'], 'string', 'max' => 4],
            [['grouper_version'], 'string', 'max' => 20],
            [['an'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'vn' => 'Vn',
            'an' => 'An',
            'hn' => 'Hn',
            'ward' => 'Ward',
            'rgtdate' => 'Rgtdate',
            'rgttime' => 'Rgttime',
            'pttype' => 'Pttype',
            'prediag' => 'Prediag',
            'dchdate' => 'Dchdate',
            'daycnt' => 'Daycnt',
            'dchtime' => 'Dchtime',
            'dchstts' => 'Dchstts',
            'dchtype' => 'Dchtype',
            'dthdiagdct' => 'Dthdiagdct',
            'ipdlct' => 'Ipdlct',
            'bmi' => 'Bmi',
            'bw' => 'Bw',
            'height' => 'Height',
            'tt' => 'Tt',
            'rr' => 'Rr',
            'pr' => 'Pr',
            'sbp' => 'Sbp',
            'dbp' => 'Dbp',
            'ipttype' => 'Ipttype',
            'painscore' => 'Painscore',
            'symptmi' => 'Symptmi',
            'drg' => 'Drg',
            'rw' => 'Rw',
            'adjrw' => 'Adjrw',
            'error' => 'Error',
            'warning' => 'Warning',
            'actlos' => 'Actlos',
            'grouper_version' => 'Grouper Version',
            'wtlos' => 'Wtlos',
            'ot' => 'Ot',
            'dept' => 'Dept',
        ];
    }

    public function getWardadmit()
    {
        return $this->hasOne(Idpm::className(),['idpm' => 'ward']);
    }

    public function getIptadm()
    {
        return $this->hasOne(Iptadm::className(),['an' => 'an']);
    }

    public function getDctype()
    {
        return $this->hasOne(Dchtype::className(),['dchtype' => 'dchtype']);
    }
    
    public function getPt()
    {
        return $this->hasOne(Pt::className(),['hn' => 'hn']);
    }

    public function getRefer()
    {
        return $this->hasOne(Orfro::className(),['vn' => 'vn']);
    }

    public function getDcDate()
    {
        $month = array("01"=>"ม.ค.","02"=>"ก.พ","03"=>"มี.ค.","04"=>"เม.ย.","05"=>"พ.ค.","06"=>"มิ.ย.","07"=>"ก.ค.","08"=>"ส.ค.","09"=>"ก.ย.","10"=>"ต.ค.","11"=>"พ.ย.","12"=>"ธ.ค.");
        $visit = new DateTime($this->dchdate);
        $d = $visit->format('j');
        $m = $month[$visit->format('m')];
        $y = $visit->format('Y')+543;
        if(strlen($this->dchtime) == 4){
            $h = substr($this->dchtime,0,2);
            $i = substr($this->dchtime,2,2);
        } else {
            $h = '0'.substr($this->dchtime,0,1);
            $i = substr($this->dchtime,1,2);
        } 
        $result = $d.' '.$m.' '.$y.' เวลา '.$h.':'.$i.' น.';
        return $result;

    }

    public function getAdmitDate()
    {
        $month = array("01"=>"ม.ค.","02"=>"ก.พ","03"=>"มี.ค.","04"=>"เม.ย.","05"=>"พ.ค.","06"=>"มิ.ย.","07"=>"ก.ค.","08"=>"ส.ค.","09"=>"ก.ย.","10"=>"ต.ค.","11"=>"พ.ย.","12"=>"ธ.ค.");
        $visit = new DateTime($this->rgtdate);
        $d = $visit->format('j');
        $m = $month[$visit->format('m')];
        $y = $visit->format('Y')+543;
        if(strlen($this->rgttime) == 4){
            $h = substr($this->rgttime,0,2);
            $i = substr($this->rgttime,2,2);
        } else {
            $h = '0'.substr($this->rgttime,0,1);
            $i = substr($this->rgttime,1,2);
        } 
        $result = $d.' '.$m.' '.$y.' เวลา '.$h.':'.$i.' น.';
        return $result;
    }

    public static function getThaiDate($date)
    {
        $month = array("01"=>"ม.ค.","02"=>"ก.พ","03"=>"มี.ค.","04"=>"เม.ย.","05"=>"พ.ค.","06"=>"มิ.ย.","07"=>"ก.ค.","08"=>"ส.ค.","09"=>"ก.ย.","10"=>"ต.ค.","11"=>"พ.ย.","12"=>"ธ.ค.");
        if($date){
            $visit = new DateTime($date);
            $d = $visit->format('j');
            $m = $month[$visit->format('m')];
            $y = $visit->format('Y')+543;
            $result = $d.' '.$m.' '.$y;    
        } else {
            $result = 'ไม่ได้ระบุวัน';
        }
        return $result;
    }

    public static function getThaiDateTime($date)
    {
        $month = array("01"=>"ม.ค.","02"=>"ก.พ","03"=>"มี.ค.","04"=>"เม.ย.","05"=>"พ.ค.","06"=>"มิ.ย.","07"=>"ก.ค.","08"=>"ส.ค.","09"=>"ก.ย.","10"=>"ต.ค.","11"=>"พ.ย.","12"=>"ธ.ค.");
        if($date){
            $visit = new DateTime($date);
            $d = $visit->format('j');
            $m = $month[$visit->format('m')];
            $y = $visit->format('Y')+543;
            $h = $visit->format('H');
            $i = $visit->format('i');
            $result = $d.' '.$m.' '.$y.' '.$h.':'.$i.'  น.'  ;    
        } else {
            $result = 'ไม่ได้ระบุวัน';
        }
        return $result;
    }

    public function getReceive(){
        $order = DoctorOrders::find()->where(['an' => $this->an])->andWhere('receive_id is null')->one();
        if($order){
            return 'btn btn-danger btn-block';
        }   
        return 'btn btn-success btn-block';
    }

}

models/Prsc.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "prsc".
 *
 * @property int $vn
 * @property int $prscno
 * @property string $prscdate
 * @property int $prsctime
 * @property int $an
 * @property string $pttype
 * @property string $paidst
 * @property string $charge
 * @property string $dscamt
 * @property int $rcptno
 * @property string $issprsn
 * @property string $sotpdate
 * @property string $sotptime
 * @property string $pharmacist
 * @property int $consultid
 * @property string $usehome
 */
class Prsc extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'prsc';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['vn', 'prsctime', 'an', 'pttype', 'paidst', 'charge', 'dscamt', 'rcptno', 'issprsn', 'sotpdate', 'sotptime', 'pharmacist', 'consultid'], 'required'],
            [['vn', 'prsctime', 'an', 'rcptno', 'consultid'], 'integer'],
            [['prscdate'], 'safe'],
            [['charge', 'dscamt'], 'number'],
            [['pttype', 'paidst'], 'string', 'max' => 2],
            [['issprsn'], 'string', 'max' => 5],
            [['sotpdate'], 'string', 'max' => 8],
            [['sotptime'], 'string', 'max' => 4],
            [['pharmacist'], 'string', 'max' => 6],
            [['usehome'], 'string', 'max' => 1],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'vn' => 'Vn',
            'prscno' => 'Prscno',
            'prscdate' => 'Prscdate',
            'prsctime' => 'Prsctime',
            'an' => 'An',
            'pttype' => 'Pttype',
            'paidst' => 'Paidst',
            'charge' => 'Charge',
            'dscamt' => 'Dscamt',
            'rcptno' => 'Rcptno',
            'issprsn' => 'Issprsn',
            'sotpdate' => 'Sotpdate',
            'sotptime' => 'Sotptime',
            'pharmacist' => 'Pharmacist',
            'consultid' => 'Consultid',
            'usehome' => 'Usehome',
        ];
    }

    public function getDrug()
    {
        return $this->hasMany(Prscdt::className(),['prscno' => 'prscno']);
    }

}

controllers/AdmissionController.php
<?php

namespace app\controllers;

use app\models\HiSetup;
use app\models\Idpm;
use app\models\Ipt;
use app\models\Iptadm;
use app\models\IptSearch;
use app\models\Lab;
use app\models\Lbbk;
use app\models\ListIpd;
use app\models\Ovst;
use app\models\Pt;
use app\models\PtAllergy;
use app\models\Ptinfo;
use kartik\mpdf\Pdf;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

date_default_timezone_set('Asia/Bangkok');

/**
 * AdmissionController implements the CRUD actions for Ipt model.
 */
class AdmissionController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
                'access' => [
                    'class' => AccessControl::className(),
                    'rules' => [
                        [
                            'allow' => true,
                            'roles' => ['@'],
                        ]
                    ]
                ]
            ]
        );
    }

    /**
     * Lists all Ipt models.
     *
     * @return string
     */
    public function actionIndex($ward_id)
    {
        $searchModel = new IptSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);
        $dataProvider->query->andWhere(['ward' => $ward_id]);
        $dataProvider->query->andWhere(['dchdate' => '0000-00-00']);
        $ward = Idpm::find()->where(['idpm' => $ward_id])->one();
        $model = $dataProvider->getModels();
        $layout = HiSetup::find()->where(['common_code'=>'layout'])->one();
        if ($layout->value1 == 'grid'){
            return $this->render('index_grid', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
                'ward' => $ward,
                'layout' => $layout->value1,
            ]);    
        } else {
            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
                'model' => $model,
                'ward' => $ward,
                'layout' => $layout->value1,
            ]);    
        }
    }

    /**
     * Displays a single Ipt model.
     * @param int $an An
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($an)
    {
        $model = ListIpd::find()->where(['an'=>$an])->one();
        $ptinfo = Ptinfo::find()->where(['hn'=>$model->hn])->one();
        $allergy = PtAllergy::find()->where(['hn'=>$model->hn])->one();
        $visit = Ovst::find()->where(['an' => $an])->one();
        $ward = Ipt::find()->where(['an' => $an])->one();

        return $this->render('view', [
            'model' => $model,
            'ptinfo' => $ptinfo,
            'allergy' => $allergy,
            'visit' => $visit,
            'ward' => $ward,
        ]);
    }

    /**
     * Displays a single Ipt model.
     * @param int $an An
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionLab($id)
    {
        $model = ListIpd::find()->where(['an'=>$id])->one();
        $ptinfo = Ptinfo::find()->where(['hn'=>$model->hn])->one();
        $visit = Ovst::find()->where(['an' => $id])->one();
        $ward = Ipt::find()->where(['an' => $id])->one();

        return $this->render('lab', [
            'model' => $model,
            'ptinfo' => $ptinfo,
            'visit' => $visit,
            'ward' => $ward,
        ]);
    }
    /**
     * Creates a new Ipt model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Ipt();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'an' => $model->an]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Ipt model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $an An
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($an)
    {
        $model = $this->findModel($an);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'an' => $model->an]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionSwitchlayout($id)
    {
        $layout = HiSetup::find()->where(['common_code'=>'layout'])->one();
        if ($layout->value1 == 'grid'){
            $layout->value1 = 'card';
            $layout->save();
        } else {
            $layout->value1 = 'grid';
            $layout->save();
        }
        return $this->redirect(['index','ward_id' => $id]);

    }

    public function actionLayout()
    {
        $layout = HiSetup::find()->where(['common_code'=>'layout'])->one();
        if ($layout->value2 == 'grid'){
            $layout->value2 = 'card';
            $layout->save();
        } else {
            $layout->value2 = 'grid';
            $layout->save();
        }
        return $this->redirect(['user/admin/index']);

    }

    public function actionPrintLab($vn,$labcode)
    {
        $model = Lbbk::find()->where(['vn'=>$vn,'labcode'=>$labcode])->all();
        $lab = Lab::find()->where(['labcode' => $labcode])->one();
        $pt = Ipt::find()->where(['vn' => $vn])->one();
        $content = $this->renderPartial('_print',[
            'model' => $model,
            'pt' => $pt,
            'lab' => $lab, 
        ]);
        $pdf = new Pdf([
            'mode' => Pdf::MODE_UTF8,
            // A4 paper format
            'format' => Pdf::FORMAT_A4,
            // portrait orientation
            'orientation' => Pdf::ORIENT_PORTRAIT,
            // stream to browser inline
            'destination' => Pdf::DEST_BROWSER,
            // your html content input
            'content' => $content,
            // format content from your own css file if needed or use the
            // enhanced bootstrap css built by Krajee for mPDF formatting
            'cssFile' => '@app/web/css/pdf.css',
            // any css to be embedded if required
            'cssInline' => '.bd{border:1.5px solid; text-align: center;} .ar{text-align:right} .imgbd{border:1px solid}',
            // set mPDF properties on the fly
            'options' => ['title' => 'Lab : '.$pt->an],
            // call mPDF methods on the fly
            'methods' => [
                //'SetHeader'=>[''],
                //'SetFooter'=>['{PAGENO}'],
            ]
        ]);

        return $pdf->render();

    }

    /**
     * Deletes an existing Ipt model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $an An
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($an)
    {
        $this->findModel($an)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Ipt model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $an An
     * @return Ipt the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($an)
    {
        if (($model = Ipt::findOne(['an' => $an])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/admission/_print.php
<?php

use app\models\Labresult;
?>
<table calss="table_bordered" width="100%" border="1" cellpadding="2" cellspacing="0">
    <tr>
        <th colspan="3">Lab: <b><?= $lab->labname ?></b></th>
    </tr>
    <tr>
        <td width="50%"><b>&emsp; ชื่อ-สกุล </b><br>&emsp; &emsp; &emsp;<?= $pt->pt->getFullName() ?></td>
        <td width="25%">&emsp; <b>อายุ</b> <?= $pt->pt->getAge() ?><br>&emsp; <b>เพศ </b> <?= $pt->pt->getGender() ?></td>
        <td width="25%">&emsp; <b>HN:</b> <?= $pt->hn ?><br>&emsp; <b>AN:</b> <?= $pt->an ?></td>
    </tr>
</table>
<table calss="table_bordered" width="100%" border="1" cellpadding="2" cellspacing="0">
    <?php
    foreach ($model as $r) {
        $result = Labresult::find()->joinWith('label')->where(['ln' => $r->ln])->orderBy(['id' => SORT_DESC])->all();
        $row = Labresult::find()->joinWith('label')->where(['ln' => $r->ln])->orderBy(['id' => SORT_DESC])->count();
        echo '<tr><td colspan=2 align="center">วันที่' . $r->getServdate() . '</td></tr>';
        $i = 0;
        foreach ($result as $v) {
            if($i % 2 == 0 || $i == 0){
                echo '<tr>';
            }
            $i++;
            echo '<td>' . $v->getLabelName() . ': <b>' . $v->labresult . '</b> ' . $v->unit . ' [' . $v->normal . ']' . '</td>';
            if ($i % 2 == 0) {
                echo '</tr>';
            }
        }
    }
    ?>
</table>

views/admission/_search.php
<?php

use kartik\icons\Icon;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\IptSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="ipt-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index','ward_id' => $id],
        'method' => 'get',
    ]); ?>
    <div class="row">
    <div class="col-md-3 col-sm-4 col-xs-5">
    <?= $form->field($model, 'an')->textInput(['placeholder' => 'ระบุ AN'])->label(false); ?>
    </div>
    <div class="col-md-3 col-sm-4 col-xs-5">
    <?= $form->field($model, 'hn')->textInput(['placeholder' => 'ระบุ HN'])->label(false); ?>
    </div>
    <div class="col-2">
    <div class="form-group">
        <?= Html::submitButton(Icon::show('search').' ค้นหา', ['class' => 'btn btn-primary']) ?>
    </div>        
    </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/admission/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Ipt */

$this->title = 'Create Ipt';
?>
<div class="ipt-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/admission/index.php
<?php

use app\models\IptOwner;
use kartik\icons\Icon;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel app\models\AdmissionSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'ข้อมูลผู้ป่วย ' . $ward->nameidpm;
?>
<div class="admission-index">

    <div style="text-align:right">
        <?= Html::a(Icon::show('table') . 'ตาราง', ['switchlayout', 'id' => $ward->idpm], ['class' => 'btn btn-primary']) ?>
        <?php echo $this->render('_search', ['model' => $searchModel, 'id' => $ward->idpm]); ?>
    </div>
    <div class="row">
        <?php
        foreach ($model as $patient) {
            $owner = IptOwner::find()->where(['an' => $patient->an, 'owner_status' => '1'])->all();
            $ownername = '';
            if ($owner) {
                foreach ($owner as $o) {
                    $ownername = $ownername . $o->getTypeName() . ':' . $o->profile->fullname . '<br>';
                }
            } else {
                $ownername = 'ยังไม่ระบุแพทย์';
            }
        ?>
            <div class="col-md-6 col-lg-4">
                <div <?= $patient->pt->getGender() == 'ชาย' ? 'class="card text-black" style="background:#C4DDFF"' : 'class="card text-black " style="background:#F9CEEE"' ?>>
                    <div class="card-header">
                        <div class="row">
                            <div class="col-6">
                                <b>AN <?= $patient->an ?>
                            </div>
                            <div class="col-6">
                                <div style="text-align:right">เตียง <?= $patient->iptadm->getBedName() ? $patient->iptadm->getBedName() : 'ยังไม่ระบุเตียง' ?></div></b>
                            </div>
                            <div class="col-10">
                                <?= $ownername ?>
                            </div>
                            <div class="col-2">
                                <?= Html::a(Icon::show('plus'), ['owner/index', 'an' => $patient->an, 'ward' => $ward->idpm], ['class' => 'btn btn-success']) ?>
                            </div>
                        </div>

                    </div>
                    <div class="card-body">
                        <b>HN : <?= $patient->hn ?> </b> <br>
                        <b>ชื่อ-สกุล :</b> <?= $patient->pt->getFullName() ?>
                        <br>
                        <b>เลขบัตรประชาชน :</b> <?= $patient->pt->pop_id ?>
                        <br>
                        <b>เพศ : </b><?= $patient->pt->getGender() ?> &emsp; <b>อายุ : </b><?= $patient->pt->getAge() ?>
                        <br>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col-4">
                                <?= Html::a('ดูข้อมูล', ['view', 'an' => $patient->an], ['class' => 'btn btn-info btn-block']) ?>
                            </div>
                            <div class="col-4">
                                <?= Html::a('Orders', ['order/list', 'id' => $patient->an], ['class' => $patient->getReceive()]) ?>
                            </div>
                            <div class="col-4">
                                <?= Html::a('Notes', ['note/list', 'id' => $patient->an], ['class' => 'btn btn-warning btn-block']) ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php
        }
        ?>
    </div>
</div>

views/admission/view.php
<?php

use app\models\Labresult;
use app\models\Lbbk;
use kartik\icons\Icon;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Ipt */

$this->title = 'AN: '.$model->an;
\yii\web\YiiAsset::register($this);
?>
<div class="ipt-view">
  <div class="row">
    <div class="col-10 offset-2">
    <?= Html::a(Icon::show('chevron-left').'กลับ', ['index','ward_id' => $ward->ward], ['class' => 'btn btn-danger']) ?>
    &emsp; <?= $ward->dchdate == '0000-00-00' ? Html::a(Icon::show('plus').'เพิ่ม Order', ['order/create','an'=>$model->an], ['class' => 'btn btn-success']):'' ?>
    &emsp; <?= Html::a(Icon::show('flask').'Lab', ['lab','id'=>$model->an], ['class' => 'btn btn-primary']) ?>
    &emsp; <?= Html::a(Icon::show('clipboard').'Doctor Order', ['order/list','id'=>$model->an], ['class' => 'btn btn-info']) ?>
    &emsp; <?= Html::a(Icon::show('notes-medical').'Nurse Note', ['note/list','id'=>$model->an], ['class' => 'btn btn-warning']) ?>
    </div>
  </div>
  <br>
<div class="card text-white bg-primary">
  <div class="card-header">ข้อมูลทั่วไป</div>
  <div class="card-body bg-white">
    <p class="card-text">
      &emsp;<b>HN: <?php echo $model->hn; ?></b>
      &emsp;<b>AN: <?php echo $model->an; ?></b>
      &emsp;<b>ชื่อ-สกุล: </b><?php echo $model->prename . $model->ptname; ?>
      &emsp;<b>อายุ </b><?php echo $model->age; ?> ปี
      &emsp;<b>เพศ </b><?php echo $ptinfo->sex; ?>
    </p>
  </div>
</div>
<div class="card-group">
<div class="card text-white bg-info">
  <div class="card-header">ประวัติ</div>
  <div class="card-body bg-white">
    <p class="card-text">
      &emsp;<b>Chief Compaint: </b>
      <?= $model->cc; ?><br>
      &emsp;<b>Present Illness: </b>
      <?= $model->pi; ?><br>
      &emsp;<b>Past History: </b>
      <?= $model->ph ?><br>
      &emsp;<b>ประวัติการแพ้ยา: </b>
      &emsp;<?= $allergy ? $allergy->drug:'-' ?><br>
      &emsp;<b>การตั้งครรภ์: </b>
      <?= $visit->preg == '1' ? 'ตั้งครรภ์':'-' ?><br>
    </p>
  </div>
</div>
<div class="card text-white bg-success">
  <div class="card-header">การรับรักษา</div>
  <div class="card-body bg-white">
    <p class="card-text">
      <h3>Previous Diagnosis : </h3>
      &emsp;<?php echo str_replace(', unspecified','',$model->prediag); ?><br>
      <h3>Vital Sign</h3>
      &emsp;<b>BT:</b> <?php echo $model->tt; ?> ºC
      <b>BP:</b> <?php echo $model->sbp . '/' . $model->dbp; ?> mmHg
      <b>PR:</b> <?php echo $model->pr ?> /m
      <b>RR:</b> <?php echo $model->rr ?> /m
      <b>น้ำหนัก:</b> <?php echo $model->bw ?> kg
      <b>ส่วนสูง:</b> <?php echo $model->height ?> cm <br><br>
      <h3>ผลการตรวจร่างกาย</h3>
      &emsp;<b>PE:</b> <?php echo $model->pe ?><br>
    </p>
  </div>
</div>
</div>