models/Pt.php
<?php

namespace app\models;

use Yii;
use DateTime;
/**
 * This is the model class for table "pt".
 *
 * @property int $hn
 * @property string $pname
 * @property string $fname
 * @property string $lname
 * @property string $brthdate
 * @property int $truebrth
 * @property string $dthdate
 * @property string $male
 * @property string $ctzshp
 * @property string $ntnlty
 * @property string $rlgn
 * @property string $occptn
 * @property string $bloodgrp
 * @property string $allergy
 * @property string $addrpart
 * @property string $moopart
 * @property string $tmbpart
 * @property string $amppart
 * @property string $chwpart
 * @property string $hometel
 * @property string $pttype
 * @property string $mrtlst
 * @property string $spsname
 * @property string $mthname
 * @property string $fthname
 * @property string $offaddr
 * @property string $offtel
 * @property string $infmname
 * @property string $prsnrlt
 * @property string $infmaddr
 * @property string $infmtel
 * @property string $opdlct
 * @property string $fdate
 * @property string $ldate
 * @property string $pop_id
 * @property string $height
 * @property string $register
 * @property string $pathimage
 * @property string $typearea
 * @property string $statusinfo
 * @property string $house_id
 * @property string $housetype
 * @property string $viptype
 * @property string $cidlabor
 * @property string $engfname
 * @property string $englname
 * @property string $engpname
 * @property string $familyno
 * @property string $father_cid
 * @property string $mother_cid
 * @property string $couple_cid
 * @property string $family_pos
 * @property string $movein
 * @property string $moveout
 * @property string $typedisch
 * @property string $labor
 * @property string $passport
 * @property string $vstatus
 * @property string $gencid
 * @property string $education
 * @property string $couple
 */
class Pt extends \yii\db\ActiveRecord
{
    public $total;
    
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'pt';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['pname', 'truebrth', 'male', 'ctzshp', 'ntnlty', 'rlgn', 'occptn', 'bloodgrp', 'allergy', 'addrpart', 'moopart', 'tmbpart', 'amppart', 'chwpart', 'hometel', 'pttype', 'mrtlst', 'spsname', 'mthname', 'fthname', 'offaddr', 'offtel', 'infmname', 'prsnrlt', 'infmaddr', 'infmtel', 'opdlct', 'pop_id', 'height', 'register', 'statusinfo', 'house_id', 'housetype', 'viptype', 'cidlabor', 'engfname', 'englname', 'engpname', 'father_cid', 'mother_cid', 'couple_cid', 'passport', 'vstatus', 'gencid', 'education', 'couple'], 'required'],
            [['brthdate', 'dthdate', 'fdate', 'ldate', 'movein', 'moveout'], 'safe'],
            [['truebrth'], 'integer'],
            [['height'], 'number'],
            [['typearea'], 'string'],
            [['pname'], 'string', 'max' => 15],
            [['fname', 'lname'], 'string', 'max' => 25],
            [['male', 'rlgn', 'mrtlst', 'housetype', 'family_pos', 'typedisch', 'vstatus'], 'string', 'max' => 1],
            [['ctzshp', 'ntnlty', 'bloodgrp', 'moopart', 'tmbpart', 'amppart', 'chwpart', 'pttype', 'register', 'viptype', 'labor', 'education'], 'string', 'max' => 2],
            [['occptn'], 'string', 'max' => 3],
            [['allergy'], 'string', 'max' => 60],
            [['addrpart', 'spsname', 'mthname', 'fthname', 'infmname'], 'string', 'max' => 30],
            [['hometel', 'offtel', 'infmtel', 'cidlabor', 'passport'], 'string', 'max' => 20],
            [['offaddr', 'infmaddr'], 'string', 'max' => 150],
            [['prsnrlt'], 'string', 'max' => 10],
            [['opdlct'], 'string', 'max' => 5],
            [['pop_id', 'familyno', 'father_cid', 'mother_cid', 'couple_cid', 'gencid'], 'string', 'max' => 13],
            [['pathimage', 'couple'], 'string', 'max' => 100],
            [['statusinfo', 'engfname', 'englname', 'engpname'], 'string', 'max' => 40],
            [['house_id'], 'string', 'max' => 11],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'hn' => 'Hn',
            'pname' => 'Pname',
            'fname' => 'Fname',
            'lname' => 'Lname',
            'brthdate' => 'Brthdate',
            'truebrth' => 'Truebrth',
            'dthdate' => 'Dthdate',
            'male' => 'Male',
            'ctzshp' => 'Ctzshp',
            'ntnlty' => 'Ntnlty',
            'rlgn' => 'Rlgn',
            'occptn' => 'Occptn',
            'bloodgrp' => 'Bloodgrp',
            'allergy' => 'Allergy',
            'addrpart' => 'Addrpart',
            'moopart' => 'Moopart',
            'tmbpart' => 'Tmbpart',
            'amppart' => 'Amppart',
            'chwpart' => 'Chwpart',
            'hometel' => 'Hometel',
            'pttype' => 'Pttype',
            'mrtlst' => 'Mrtlst',
            'spsname' => 'Spsname',
            'mthname' => 'Mthname',
            'fthname' => 'Fthname',
            'offaddr' => 'Offaddr',
            'offtel' => 'Offtel',
            'infmname' => 'Infmname',
            'prsnrlt' => 'Prsnrlt',
            'infmaddr' => 'Infmaddr',
            'infmtel' => 'Infmtel',
            'opdlct' => 'Opdlct',
            'fdate' => 'Fdate',
            'ldate' => 'Ldate',
            'pop_id' => 'Pop ID',
            'height' => 'Height',
            'register' => 'Register',
            'pathimage' => 'Pathimage',
            'typearea' => 'Typearea',
            'statusinfo' => 'Statusinfo',
            'house_id' => 'House ID',
            'housetype' => 'Housetype',
            'viptype' => 'Viptype',
            'cidlabor' => 'Cidlabor',
            'engfname' => 'Engfname',
            'englname' => 'Englname',
            'engpname' => 'Engpname',
            'familyno' => 'Familyno',
            'father_cid' => 'Father Cid',
            'mother_cid' => 'Mother Cid',
            'couple_cid' => 'Couple Cid',
            'family_pos' => 'Family Pos',
            'movein' => 'Movein',
            'moveout' => 'Moveout',
            'typedisch' => 'Typedisch',
            'labor' => 'Labor',
            'passport' => 'Passport',
            'vstatus' => 'Vstatus',
            'gencid' => 'Gencid',
            'education' => 'Education',
            'couple' => 'Couple',
        ];
    }

    public function getAge()
    {
        $dob = new DateTime($this->brthdate);
        $today = new DateTime('today');
        $age = $dob->diff($today)->y;
        return $age.' ปี';
    }

    public function getFullname()
    {
        $dob = new DateTime($this->brthdate);
        $today = new DateTime('today');
        $age = $dob->diff($today)->y;
        if($this->pname == '') {
            if($this->male == '1' && $age < 15 ) {
                $this->mrtlst <> '6' ? $this->pname = 'ด.ช.': $this->pname = 'เณร';
            }  
            if($this->male == '1' && $age >= 15 ) {
                $this->mrtlst <> '6' ? $this->pname = 'นาย': $this->pname = 'พระ';
            }
            if($this->male == '2' && $age >= 15 ) {
                $this->mrtlst == '2' ? $this->pname = 'นาง': $this->pname = 'นางสาว';
            }
            if($this->male == '2' && $age >= 15 && $this->mrtlst == '6' ) {
                $this->pname = 'แม่ชี';
            }  
            if($this->male == '2' && $age < 15 ) {
                $this->pname = 'ด.ญ.';
            }
        }  
        return $this->pname.$this->fname.' '.$this->lname;
    }

    public function getฺBirthdate()
    {
        $month = array("01"=>"ม.ค.","02"=>"ก.พ","03"=>"มี.ค.","04"=>"เม.ย.","05"=>"พ.ค.","06"=>"มิ.ย.","07"=>"ก.ค.","08"=>"ส.ค.","09"=>"ก.ย.","10"=>"ต.ค.","11"=>"พ.ย.","12"=>"ธ.ค.");
        $visit = new DateTime($this->brthdate);
        $d = $visit->format('j');
        $m = $month[$visit->format('m')];
        $y = $visit->format('Y')+543;
        $result = $d.' '.$m.' '.$y;
        return $result;
    }

    public function getGender(){
        return $this->male == '1' ? 'ชาย':'หญิง';
    }

    public function getType()
    {
        return $this->hasOne(Pttype::className(),['pttype' => 'pttype']);
    }

}

models/User.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "user".
 *
 * @property int $id
 * @property string $username
 * @property string $email
 * @property string $password_hash
 * @property string $auth_key
 * @property int|null $confirmed_at
 * @property string|null $unconfirmed_email
 * @property int|null $blocked_at
 * @property string|null $registration_ip
 * @property int $created_at
 * @property int $updated_at
 * @property int $flags
 * @property int|null $last_login_at
 * @property int|null $role
 *
 */
class User extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['username', 'email', 'password_hash', 'auth_key', 'created_at', 'updated_at'], 'required'],
            [['confirmed_at', 'blocked_at', 'created_at', 'updated_at', 'flags', 'last_login_at', 'role'], 'integer'],
            [['username', 'email', 'unconfirmed_email'], 'string', 'max' => 255],
            [['password_hash'], 'string', 'max' => 60],
            [['auth_key'], 'string', 'max' => 32],
            [['registration_ip'], 'string', 'max' => 45],
            [['username'], 'unique'],
            [['email'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'email' => 'Email',
            'password_hash' => 'Password Hash',
            'auth_key' => 'Auth Key',
            'confirmed_at' => 'Confirmed At',
            'unconfirmed_email' => 'Unconfirmed Email',
            'blocked_at' => 'Blocked At',
            'registration_ip' => 'Registration Ip',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'flags' => 'Flags',
            'last_login_at' => 'Last Login At',
            'role' => 'Role',
        ];
    }

    /**
     * Gets query for [[Tokens]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTokens()
    {
        return $this->hasMany(Token::className(), ['user_id' => 'id']);
    }

    public function getProfile()
    {
        return $this->hasOne(Profile::className(), ['user_id' => 'id']);
    }
}

views/note/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Rounds;
use kartik\date\DatePicker;
use kartik\icons\Icon;
use yii\widgets\MaskedInput;

/* @var $this yii\web\View */
/* @var $model app\models\Notes */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="notes-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="card bg-primary">
        <div class="card-header">
            <div class="row">
                <div class="col-md-4 col-sm-6 col-xs-6">
                    <?= $form->field($model, 'note_date')->widget(
                        DatePicker::ClassName(),
                        [
                            'name' => 'วันที่บันทึก',
                            'type' => DatePicker::TYPE_COMPONENT_APPEND,
                            'options' => ['placeholder' => 'ระบุวัน'],
                            'pluginOptions' => [
                                'format' => 'yyyy-mm-dd',
                                'todayHighlight' => true
                            ]
                        ]
                    )->label(false);
                    ?>
                </div>
                <div class="col-md-3 col-sm-4 col-xs-6">
                    <?= $form->field($model, 'note_time')->widget(
                        MaskedInput::className(),
                        [
                            'mask' => '99:99'
                        ]
                    )->label(false);
                    ?>
                </div>
            </div>
        </div>
        <div class="card-body bg-light">
            <div class="row">
                <div class="col-12">
                    <?= $form->field($model, 'problem')->textarea(['rows' => 3, 'placeholder' => 'บันทึกปัญหาที่พบในการดูแลผู้ป่วย ...'])->label('ปัญหา (Problem)') ?>
                </div>
                <div class="col-12">
                    <?= $form->field($model, 'activity_select')->checkboxList($model->getActUse(), ['item' => function ($index, $label, $name, $checked, $value) {
                        return "<label class='col-12'><input type='checkbox' {$checked} name='{$name}' value='{$value}'> {$label} </label>";
                    }])->label('กิจกรรมทางการพยาบาล (Nurse Activity)') ?>
                </div>
                <div class="col-12">
                    <?= $form->field($model, 'activity')->textarea(['rows' => 3, 'placeholder' => 'บันทึกกิจกรรมการดูแลผู้ป่วย ...'])->label('กิจกรรมเพิ่มเติม') ?>
                </div>
                <div class="col-12">
                    <?= $form->field($model, 'evaluate_select')->checkboxList($model->getEvaUse(), ['item' => function ($index, $label, $name, $checked, $value) {
                        return "<label class='col-12'><input type='checkbox' {$checked} name='{$name}' value='{$value}'> {$label} </label>";
                    }])->label('การประเมินผู้ป่วยหลังทำกิจกรรมทางการพยาบาล (Nurse Evaluate)') ?>
                </div>
                <div class="col-12">
                    <?= $form->field($model, 'evaluate')->textarea(['rows' => 3, 'placeholder' => 'บันทึกการประเมินผู้ป่วยหลังทำกิจกรรม ...'])->label('การประเมินเพิ่มเติม') ?>
                </div>
            </div>
        </div>
        <div class="card-footer bg-light">
            <div class="form-group" style="text-align: center;">
                <?= Html::submitButton(Icon::show('save') . ' บันทึก', ['class' => 'btn btn-success', 'style' => 'width:200px']) ?>
                &emsp;
                <?= Html::a(Icon::show('chevron-left') . ' กลับไปหน้าหลัก', ['list', 'id' => $model->an], ['class' => 'btn btn-danger', 'style' => 'width:200px']) ?>
            </div>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/note/_form_vs.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\models\Rounds;
use kartik\date\DatePicker;
use kartik\icons\Icon;
use yii\widgets\MaskedInput;

$round = [2 => 'รอบ 2.00 น.', 6 => 'รอบ 6.00 น.', 10 => 'รอบ 10.00 น.', 14 => 'รอบ 14.00 น.', 18 => 'รอบ 18.00 น.', 22 => 'รอบ 22.00 น.'];

/* @var $this yii\web\View */
/* @var $model app\models\Notes */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="notes-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="card bg-primary">
        <div class="card-header">
            <div class="row">
            <div class="col-3" style="text-align:right;">เวลาที่วัด: </div>
            <div class="col-3">
                    <?= $form->field($model,'record_time')->widget(
                        MaskedInput::className(),
                        [
                            'mask' => '99:99'
                        ])->label(false); 
                    ?>
                </div>
            </div>
        </div>
        <div class="card-body bg-light">
            <div class="card">
                <div class="card-header">Vital Sign</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-1" style="text-align:right;">BT:</div>
                        <div class="col-1">
                            <?= $form->field($model, 'tt')->textInput()->label(false) ?>
                        </div>
                        <div class="col-1" style="text-align:right;">PR:</div>
                        <div class="col-1">
                            <?= $form->field($model, 'pr')->textInput()->label(false) ?>
                        </div>
                        <div class="col-1" style="text-align:right;">RR:</div>
                        <div class="col-1">
                            <?= $form->field($model, 'rr')->textInput()->label(false) ?>
                        </div>
                        <div class="col-1" style="text-align:right;">BP:</div>
                        <div class="col-2">
                            <?= $form->field($model, 'sbp')->textInput()->label(false) ?>
                        </div>
                        <div class="col-1" style="text-align:right;">/</div>
                        <div class="col-2">
                            <?= $form->field($model, 'dbp')->textInput()->label(false) ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">Intake (ml)</div>
                <div class="card-body">
                    <div class="row">
                    <div class="col-2" style="text-align:right;">Oral:</div>
                        <div class="col-4">
                            <?= $form->field($model, 'oral_fluid')->textInput()->label(false) ?>
                        </div>
                        <div class="col-2" style="text-align:right;">parenteral:</div>
                        <div class="col-4">
                            <?= $form->field($model, 'parenteral')->textInput()->label(false) ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">Outtake (ml)</div>
                <div class="card-body">
                    <div class="row">
                    <div class="col-2" style="text-align:right;">Urine:</div>
                        <div class="col-4">
                            <?= $form->field($model, 'urine_fluid')->textInput()->label(false) ?>
                        </div>
                        <div class="col-2" style="text-align:right;">Emesis:</div>
                        <div class="col-4">
                            <?= $form->field($model, 'emesis')->textInput()->label(false) ?>
                        </div>
                        <div class="col-2" style="text-align:right;">Drainage:</div>
                        <div class="col-4">
                            <?= $form->field($model, 'drainage')->textInput()->label(false) ?>
                        </div>
                        <div class="col-2" style="text-align:right;">Aspiration:</div>
                        <div class="col-4">
                            <?= $form->field($model, 'aspiration')->textInput()->label(false) ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">Stool/Urine (ครั้ง)</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-2" style="text-align:right;">Urine:</div>
                        <div class="col-4">
                            <?= $form->field($model, 'u')->textInput()->label(false) ?>
                        </div>
                        <div class="col-2" style="text-align:right;">Stool:</div>
                        <div class="col-4">
                            <?= $form->field($model, 's')->textInput()->label(false) ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer bg-light">
            <div class="form-group" style="text-align: center;">
                <?= Html::submitButton(Icon::show('save') . ' บันทึก', ['class' => 'btn btn-success', 'style' => 'width:150px']) ?>

                <?= Html::a(Icon::show('chevron-left') . ' กลับไปหน้าหลัก', ['list', 'id' => $model->an], ['class' => 'btn btn-danger', 'style' => 'width:150px']) ?>
            </div>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/note/_print.php
<?php

use yii\helpers\Html;
use app\models\VsDaily;
use app\models\Admission;
use app\models\Ipt;

function thaimonth($m)
{
  switch ($m) {
    case '01':
      $thainame = 'มกราคม';
      break;
    case '02':
      $thainame = 'กุมภาพันธ์';
      break;
    case '03':
      $thainame = 'มีนาคม';
      break;
    case '04':
      $thainame = 'เมษายน';
      break;
    case '05':
      $thainame = 'พฤษภาคม';
      break;
    case '06':
      $thainame = 'มิถุนายน';
      break;
    case '07':
      $thainame = 'กรกฎาคม';
      break;
    case '08':
      $thainame = 'สิงหาคม';
      break;
    case '09':
      $thainame = 'กันยายน';
      break;
    case '10':
      $thainame = 'ตุลาคม';
      break;
    case '11':
      $thainame = 'พฤศจิกายน';
      break;
    case '12':
      $thainame = 'ธันวาคม';
      break;
  }
  return $thainame;
}
?>
<?php
$i = 1;
foreach ($model as $note) {
  if ($i <> 1) {
    echo '<pagebreak>';
  }
  $i++;
?>
  <h3 align="center"><?= $office->value2 ?><br><?= $office->value3 ?> <?= $office->values4 ?>
    <br>บันทึกทางการพยาบาล
  </h3>
  <table calss="table_bordered" width="100%" border="1" cellpadding="2" cellspacing="0">
    <tr>
      <td width="35%"><b>&emsp; ชื่อ-สกุล </b><br>&emsp; &emsp; &emsp;<?= $pt->pt->getFullName() ?></td>
      <td width="35%">&emsp; <b>อายุ</b> <?= $pt->pt->getAge() ?> ปี<br>&emsp; <b>เพศ </b> <?= $pt->pt->getGender() ?></td>
      <td width="30%">&emsp; <b>HN:</b> <?= $pt->hn ?><br>&emsp; <b>AN:</b> <?= $pt->an ?></td>
    </tr>
  </table>
  <table calss="table_bordered" width="100%" border="1" cellpadding="2" cellspacing="0">
    <tr>
      <th width="20%">Date/Time</th>
      <th width="20%">Problem</th>
      <th width="25%">Activity</th>
      <th width="35%">Evaluate</th>
    </tr>
    <tr>
      <td height=720 valign=top align="center">
        <?= Ipt::getThaiDate($note->note_date) . '<br>' . $note->note_time . ' น.' ?>
        <br>
      </td>
      <td valign=top style="padding:5px;">
        <?= $note->activity_select ? $note->getActName() : '' ?>
        <?= nl2br($note->activity) ?>
      </td>
      <td style="vertical-align:top;padding:5px;">
        <?= $note->evaluate_select ? $note->getEvaname() : '' ?>
        <?= nl2br($note->activity) ?>
      </td>
      <td valign=top style="padding:5px;">
        &emsp;<?= nl2br($note->evaluate) ?><br>
        <br><b>ผู้ประเมิน</b><br><br>
        <?= $note->profile->fullname ?><br>
        <?= $note->profile->position ?><br>

      </td>
    </tr>
  </table>
<?php
}
?>

views/note/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\NurseNotesSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="nurse-notes-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'note_id') ?>

    <?= $form->field($model, 'note_date') ?>

    <?= $form->field($model, 'note_time') ?>

    <?= $form->field($model, 'activity') ?>

    <?= $form->field($model, 'evaluate') ?>

    <?php // echo $form->field($model, 'user_id') ?>

    <?php // echo $form->field($model, 'd_update') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/note/add-vs.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\NurseNotes */

$this->title = 'บันทึก Vital Sign';
?>
<div class="vital-sign-create">

    <?= $this->render('_form_vs', [
        'model' => $model,
    ]) ?>

</div>

views/note/list.php
<?php

use app\models\Ipt;
use app\models\VsDaily;
use kartik\icons\Icon;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\AdmissionSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Nurse Note AN:' . $an . ' ชื่อ-สกุล:' . $ward->pt->getFullName();
?>
<div class="admission-index">

    <p>
        <?= Html::a(Icon::show('chevron-left') . 'Home', ['admission/index', 'ward_id' => $ward->ward], ['class' => 'btn btn-danger']) ?>
        <?= in_array(Yii::$app->user->identity->role,[3,9]) ? Html::a(Icon::show('plus') . 'เพิ่ม Note', ['create', 'an' => $an], ['class' => 'btn btn-success']) : '' ?>
        <?= in_array(Yii::$app->user->identity->role,[3,9]) && $order->value1 == 'asc' ? Html::a(Icon::show('sort-amount-down') . 'เรียง Z > A', ['switchsort', 'id' => $an], ['class' => 'btn btn-primary']) : Html::a(Icon::show('sort-amount-down-alt') . 'เรียง A > Z', ['switchsort', 'id' => $an], ['class' => 'btn btn-primary']); ?>
        <?= in_array(Yii::$app->user->identity->role,[3,9]) ? Html::a(Icon::show('flask') . 'Lab', ['admission/lab', 'id' => $an], ['class' => 'btn btn-warning']):'' ?>
        <?= Html::a(Icon::show('thermometer-half') . 'V/S', ['vitalsign', 'id' => $an], ['class' => 'btn btn-info']) ?>
        <?= in_array(Yii::$app->user->identity->role,[1,3,9]) ? Html::a(Icon::show('plus') . Icon::show('thermometer-half') . 'V/S', ['add-vs', 'an' => $an], ['class' => 'btn btn-success']) : '' ?>
        <?= in_array(Yii::$app->user->identity->role,[3,5,6,7,8,9]) ? Html::a(Icon::show('notes-medical') . 'Doctor Order ', ['order/list', 'id' => $an], ['class' => 'btn btn-primary']):'' ?>
        <?= Html::a(Icon::show('print') . ' พิมพ์', ['print', 'id' => $an], ['class' => 'btn btn-warning', 'target' => '_blank']) ?>
    </p>


    <table width="100%" border="1">
        <tr>
            <th width="15%" style="text-align:center">Date/Time</th>
            <th width="20%" style="text-align:center">Problem</th>
            <th width="30%" style="text-align:center">Activity</th>
            <th width="35%" style="text-align:center">Evaluate</th>
        </tr>
        <?php
        if ($model) {
            foreach ($model as $note) {
        ?>
                <tr>
                    <td style="vertical-align:top;text-align:center">
                        <?= Ipt::getThaiDate($note->note_date) ?><br>
                        <?= $note->note_time ?> น.<br>
                    </td>
                    <td style="vertical-align:top;padding:5px;">
                        <?= nl2br($note->problem) ?>
                    </td>
                    <td style="vertical-align:top;padding:5px;">
                        <?= $note->activity_select ? $note->getActName(): '' ?>
                        <?= nl2br($note->activity) ?>
                    </td>
                    <td style="vertical-align:top;padding:5px;">
                        <?= $note->evaluate_select ? $note->getEvaname():'' ?>
                        <?= nl2br($note->evaluate) ?>
                        <br><br>
                        <b>ผู้ประเมิน</b>
                        &emsp; <?= $note->profile->fullname ?><br>
                        &emsp; <?= $note->profile->position ?><br>
                        &emsp;<?= Yii::$app->user->identity->id == $note->user_id && $note->note_date == date('Y-m-d') ? Html::a('แก้ไขบันทึก', ['update', 'note_id' => $note->note_id], ['class' => 'btn btn-warning']) : '' ?><br>
                    </td>
                </tr>
        <?php
            }
        }
        ?>
    </table>

</div>